# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./project/udagram-api-feed
- docker build -t udagram-api-user ./project/udagram-api-user
- docker build -t udagram-frontend ./project/udagram-frontend
- docker build -t reverseproxy ./project/reverseproxy
# Do similar for other three images

# Tagging
- docker tag udagram-api-feed mtsown/udagram-api-feed:v1
- docker tag udagram-api-user mtsown/udagram-api-user:v1
- docker tag udagram-frontend mtsown/udagram-frontend:v1
- docker tag reverseproxy mtsown/reverseproxy:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push mtsown/udagram-api-feed:v1
- docker push mtsown/udagram-api-user:v1
- docker push mtsown/udagram-frontend:v1
- docker push mtsown/reverseproxy:v1
# Do similar for other three images